"""Build a self-contained APPROACH.html (figure embedded as base64) for sharing."""
import base64, os

BASE = r"C:\Users\Mahmoudabujadallah\final_agantic_bugfixes"
img = os.path.join(BASE, "methodology_figure.png")
with open(img, "rb") as f:
    b64 = base64.b64encode(f.read()).decode("ascii")

html = f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>How AI Coding Agents Fix Bugs Over Time — Approach</title>
<style>
  body {{ font-family: Georgia, 'Times New Roman', serif; max-width: 820px; margin: 40px auto;
          padding: 0 24px; color: #1a1a1a; line-height: 1.55; }}
  h1 {{ font-size: 24px; border-bottom: 2px solid #333; padding-bottom: 8px; }}
  h2 {{ font-size: 18px; margin-top: 28px; }}
  figure {{ text-align: center; margin: 24px 0; }}
  figure img {{ max-width: 100%; border: 1px solid #ddd; }}
  figcaption {{ font-size: 13px; color: #555; text-align: left; margin-top: 8px; font-style: italic; }}
  table {{ border-collapse: collapse; width: 100%; font-size: 14px; margin: 14px 0; }}
  th, td {{ border: 1px solid #ccc; padding: 6px 10px; text-align: left; }}
  th {{ background: #f2f2f2; }}
  code {{ background: #f4f4f4; padding: 1px 4px; border-radius: 3px; font-size: 13px; }}
  .lead {{ color: #333; }}
  @media print {{ body {{ margin: 0; }} }}
</style></head><body>

<h1>How AI Coding Agents Fix Bugs Over Time — Approach</h1>

<p class="lead"><strong>Follow-up to our MSR'26 paper</strong>
<em>"Understanding the Rejection of Fixes Generated by Agentic Pull Requests."</em>
The paper studied a single snapshot of why AI-agent pull-request (PR) fixes get rejected; here we
add a <strong>time axis</strong> and broaden the study to eight research questions over a 15-month window.</p>

<p><strong>Data.</strong> 422,618 bug-fix PRs (Dec 2024 – Feb 2026) from the GitHub-Agentic-PR-Dataset:
121,832 written by AI agents (Claude Code, Cursor, Copilot, Devin) and 300,786 by humans.</p>

<figure>
  <img src="data:image/png;base64,{b64}" alt="Methodology diagram">
  <figcaption><strong>Figure 1. Study design.</strong> One dataset is split into agent and human
  fixes. A fairness check shows that the <strong>project type</strong>, not just authorship, drives
  rejection, which motivates a <strong>matched-repo design</strong>: every agent-vs-human question is
  answered only inside the 1,218 repositories that contain both kinds of fixes. Agent-only questions
  use the full agent data. Three shared data layers (PR metadata, file changes, commit messages) feed
  the eight research questions.</figcaption>
</figure>

<h2>Approach</h2>

<p><strong>1. Conservative, explicit outcome definitions.</strong> A PR is <em>rejected</em> only if
it was closed <strong>and</strong> never merged. The <em>rejection rate</em> is computed over
<strong>decided</strong> PRs (merged or closed) only — still-open PRs are excluded so unknown
outcomes cannot bias the rate.</p>

<p><strong>2. Matched-repo design (the central idea).</strong> Agents and humans do not work on the
same projects, so a naive comparison confounds <em>who wrote the fix</em> with <em>which project it
lives in</em>. We first confirm this matters: in repos containing both kinds of fixes the rejection
rates are 18.1% (agent) / 15.1% (human), whereas in single-type repos they fall to 14.7% / 10.9%. We
therefore restrict every agent-vs-human question to the <strong>1,218 repositories that contain
both</strong> (agent n = 47,925, human n = 287,358), so any difference reflects agent vs human rather
than the project. Agent-only questions use the full agent data.</p>

<p><strong>3. Three data layers.</strong> PR metadata (state, dates, author), file-level changes
(deriving fix size, test files, and instruction files via regex), and commit messages (revert
detection).</p>

<p><strong>4. Eight research questions.</strong></p>
<table>
<tr><th>RQ</th><th>Question</th><th>Set</th></tr>
<tr><td>RQ1a</td><td>Does the rejection rate change over time?</td><td>matched</td></tr>
<tr><td>RQ1b</td><td>Do fixes get bigger or smaller over time?</td><td>matched</td></tr>
<tr><td>RQ4</td><td>Once merged, do fixes get undone (reverted)?</td><td>matched</td></tr>
<tr><td>RQ5</td><td>Which bug types are agents good/bad at?</td><td>matched</td></tr>
<tr><td>RQ6</td><td>Does adding a test make a fix more likely to be accepted?</td><td>matched</td></tr>
<tr><td>RQ2a</td><td>Do people switch which agent they use?</td><td>all agents</td></tr>
<tr><td>RQ2b</td><td>When an agent fix is rejected, does switching agents rescue it?</td><td>all agents</td></tr>
<tr><td>RQ3</td><td>Are developers adding agent instruction files over time?</td><td>all agents</td></tr>
</table>

<p><strong>5. Preprocessing (summary).</strong> Derive month from the creation date and drop undated
PRs; build the merged/rejected flags (treating empty / <code>"NaT"</code> / <code>"None"</code>
timestamps as <em>not merged</em>); compute per-PR code churn from added + removed lines (PRs with no
file rows are excluded from size results, not counted as zero); flag test and instruction files by
regex; link fixes to the issues they close (<code>fix/close/resolve #N</code>) for RQ2b; and detect
reverts via <code>reverts commit &lt;sha&gt;</code> in commit messages.</p>

<p><strong>6. Validation.</strong> Trends are tested with Spearman correlation; the test-inclusion
effect (RQ6) with a &chi;&sup2; test, then re-checked <strong>within churn bins</strong> to confirm
the effect is not merely a side-effect of fix size.</p>

<h2>Limitations</h2>
<ul>
<li>Agent vs human is compared only inside the 1,218 shared repos (by design).</li>
<li>RQ2b sees only the ~18% of fixes that explicitly reference an issue.</li>
<li>Revert counts are a <strong>lower bound</strong> (only PR-routed reverts are visible).</li>
<li>RQ5 bug types are keyword-derived and should be spot-checked before publishing.</li>
<li>The overall ~16% rejection rate is not directly comparable to the paper's earlier snapshot.</li>
</ul>

</body></html>
"""

out = os.path.join(BASE, "APPROACH.html")
with open(out, "w", encoding="utf-8") as f:
    f.write(html)
print("saved", out, f"({len(html)//1024} KB)")
