"""Build a self-contained APPROACH.html (figure embedded as base64) for sharing."""
import base64, os

BASE = r"C:\Users\Mahmoudabujadallah\final_agantic_bugfixes"
img = os.path.join(BASE, "methodology_figure.png")
with open(img, "rb") as f:
    b64 = base64.b64encode(f.read()).decode("ascii")

html = f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>How AI Coding Agents Fix Bugs Over Time — Study Approach</title>
<style>
  body {{ font-family: Georgia, 'Times New Roman', serif; max-width: 780px; margin: 40px auto;
          padding: 0 24px; color: #1a1a1a; line-height: 1.65; font-size: 17px; }}
  h1 {{ font-size: 25px; border-bottom: 2px solid #333; padding-bottom: 8px; line-height: 1.3; }}
  h2 {{ font-size: 19px; margin-top: 34px; color: #111; }}
  p {{ margin: 14px 0; }}
  figure {{ text-align: center; margin: 26px 0; }}
  figure img {{ max-width: 100%; border: 1px solid #ddd; }}
  figcaption {{ font-size: 14px; color: #555; text-align: left; margin-top: 10px; }}
  table {{ border-collapse: collapse; width: 100%; font-size: 15px; margin: 16px 0; }}
  th, td {{ border: 1px solid #ccc; padding: 7px 11px; text-align: left; vertical-align: top; }}
  th {{ background: #f2f2f2; }}
  code {{ background: #f4f4f4; padding: 1px 4px; border-radius: 3px; font-size: 14px;
          font-family: Consolas, 'Courier New', monospace; }}
  ul {{ margin: 14px 0; }}
  li {{ margin: 7px 0; }}
  .lead {{ color: #333; }}
  .keyidea {{ background: #f7f9fc; border-left: 4px solid #4a6fa5; padding: 14px 18px;
              margin: 18px 0; font-size: 16px; }}
  .keyidea strong {{ color: #2c4a73; }}
  @media print {{ body {{ margin: 0; font-size: 12pt; }} }}
</style></head><body>

<h1>How AI Coding Agents Fix Bugs Over Time — Study Approach</h1>

<p class="lead"><strong>What this study is.</strong> It is a follow-up to our MSR'26 paper,
<em>"Understanding the Rejection of Fixes Generated by Agentic Pull Requests."</em> That paper took
a single snapshot in time and asked <em>why</em> bug-fix pull requests (PRs) written by AI coding
agents get rejected. This study keeps the same question but adds two things: a <strong>time
axis</strong> — how does the picture change month by month? — and a <strong>wider scope</strong>,
moving from one question to eight, all over a 15-month window.</p>

<p><strong>The data.</strong> 422,618 bug-fix PRs opened between December 2024 and February 2026,
drawn from the GitHub-Agentic-PR-Dataset. Of these, 121,832 were written by AI agents (Claude Code,
Cursor, Copilot, Devin) and 300,786 were written by human developers.</p>

<figure>
  <img src="data:image/png;base64,{b64}" alt="Diagram of the study design">
  <figcaption><strong>Figure 1. How the study is organised.</strong> We start from one dataset and
  split it into agent fixes and human fixes. A fairness check (top) shows that the <em>project</em>,
  not just the author, drives whether a fix is rejected. That is why every agent-vs-human question is
  answered only inside the 1,218 projects that contain both kinds of fix (the "matched" set), while
  agent-only questions use all agent data. Every question draws on the same three layers of raw data:
  PR metadata, the file changes inside each PR, and commit messages.</figcaption>
</figure>

<h2>The main idea: compare like with like</h2>

<p>AI agents and human developers tend to work on different projects. So the obvious headline
comparison — "agent fixes are rejected X% of the time, human fixes Y%" — is misleading, because it
mixes up two separate things: <em>who wrote the fix</em> and <em>which project the fix went into</em>.
Some projects reject far more PRs than others, no matter who wrote them.</p>

<p>We checked that this really matters. In projects where both agents and humans contribute, the
rejection rates are close: <strong>18.1%</strong> for agents and <strong>15.1%</strong> for humans.
In projects where only one of them contributes, both rates fall to <strong>14.7%</strong> and
<strong>10.9%</strong>. The project clearly shapes the outcome.</p>

<div class="keyidea">
<strong>So, to take the project out of the comparison,</strong> every agent-vs-human question is
answered <strong>only inside the 1,218 projects where both agents and humans submitted bug-fix
PRs</strong> (47,925 agent fixes and 287,358 human fixes). Inside those shared projects, any
remaining difference is far more likely to reflect the author than the project. Questions that are
only about agents (for example, "do people switch agents?") use the full agent dataset.
</div>

<h2>When does a fix count as "rejected"?</h2>

<p>We use deliberately strict, simple rules so an outcome is never ambiguous:</p>
<ul>
<li>A PR counts as <strong>rejected</strong> only if it was closed <em>and</em> never merged.</li>
<li>The <strong>rejection rate</strong> is measured only over PRs that have a final decision (merged
or closed). PRs that are still open are left out, so undecided cases cannot distort the rate.</li>
</ul>

<h2>The eight research questions</h2>

<p>"Matched" means the question is answered inside the 1,218 shared projects; "all agents" means it
uses the full agent dataset.</p>
<table>
<tr><th>RQ</th><th>Question</th><th>Data used</th></tr>
<tr><td>RQ1a</td><td>Does the rejection rate change over time?</td><td>matched</td></tr>
<tr><td>RQ1b</td><td>Do fixes get bigger or smaller over time?</td><td>matched</td></tr>
<tr><td>RQ4</td><td>Once merged, do fixes later get undone (reverted)?</td><td>matched</td></tr>
<tr><td>RQ5</td><td>Which kinds of bug are agents good or bad at?</td><td>matched</td></tr>
<tr><td>RQ6</td><td>Does adding a test make a fix more likely to be accepted?</td><td>matched</td></tr>
<tr><td>RQ2a</td><td>Do people switch which agent they use?</td><td>all agents</td></tr>
<tr><td>RQ2b</td><td>When an agent fix is rejected, does switching agents rescue it?</td><td>all agents</td></tr>
<tr><td>RQ3</td><td>Are developers adding agent instruction files over time?</td><td>all agents</td></tr>
</table>

<h2>How we prepare the data</h2>

<p>From the raw PRs we derive a small number of clean signals:</p>
<ul>
<li><strong>Month.</strong> Each PR is placed in a month using its creation date; PRs with no date
are dropped.</li>
<li><strong>Outcome.</strong> Each PR is marked merged or rejected; blank or placeholder timestamps
(<code>"NaT"</code>, <code>"None"</code>) are treated as <em>not merged</em>.</li>
<li><strong>Fix size.</strong> Measured as lines added + lines removed ("code churn"). PRs with no
recorded file changes are left out of the size results rather than counted as zero.</li>
<li><strong>Tests and instruction files.</strong> Text patterns flag which PRs touch test files and
which add agent instruction files (files that tell an agent how to work in a repo).</li>
<li><strong>Linked issues.</strong> Each fix is connected to the issue it closes (phrases like
<code>fix/close/resolve #123</code>) so we can follow what happens after a rejection (RQ2b).</li>
<li><strong>Reverts.</strong> Detected by looking for <code>reverts commit &lt;id&gt;</code> in
commit messages.</li>
</ul>
<p>Full step-by-step details are in <code>METHODOLOGY.md</code>.</p>

<h2>How we check the results are real</h2>
<ul>
<li><strong>Trends over time</strong> are tested with the Spearman rank correlation — does the line
move consistently up or down, rather than wandering by chance?</li>
<li><strong>The effect of adding a test</strong> (RQ6) is tested with a &chi;&sup2; test, and then
re-checked separately within groups of similar fix size. This confirms the effect is real and not
just a side-effect of fixes being larger or smaller.</li>
</ul>

<h2>What this study cannot tell us</h2>
<ul>
<li>Agents and humans are compared only inside the 1,218 shared projects — this is by design, but it
means the comparison does not cover projects where only one of them works.</li>
<li>RQ2b can only see the roughly 18% of fixes that explicitly reference an issue.</li>
<li>Revert counts are a <strong>lower bound</strong>: only reverts that go through a PR are visible.</li>
<li>RQ5 bug categories come from keywords and should be spot-checked by hand before publishing.</li>
<li>The overall ~16% rejection rate is not directly comparable to the earlier paper's snapshot — it
comes from a much larger, more recent re-collection of data.</li>
</ul>

</body></html>
"""

out = os.path.join(BASE, "APPROACH.html")
with open(out, "w", encoding="utf-8") as f:
    f.write(html)
print("saved", out, f"({len(html)//1024} KB)")
